# -*- coding: utf-8 -*-
"""Selic

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Avu8wtn5TFlK-ifj9QMuIIslFZU7rGsW
"""

!pip install python-bcb
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd

import matplotlib.pyplot as plt

from bcb import sgs
selic = sgs.get({'selic':432}, start = '2012-01-01')

from IPython.core.pylabtools import figsize
sns.set_theme()
selic.plot(figsize = (15,10))
plt.ylabel('Taxa Selic')
plt.xlabel('Período')

